name: Trigger auto deployment for financioapistageb684

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/financioapistageb684-AutoDeployTrigger-ee04b237-405f-4eef-a14c-ea48f9d18563.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FINANCIOAPISTAGEB684_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FINANCIOAPISTAGEB684_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINANCIOAPISTAGEB684_REGISTRY_PASSWORD }}
          containerAppName: financioapistageb684
          resourceGroup: DefaultResourceGroup-WEU
          imageToBuild: btymo/financio-api-stage:${{ github.sha }}
          

     

