# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - financioapistage462d

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8fa9992a6b1744cf92d407511432bdc8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e78d5558f204427abdd280f857cce7ed }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8fa9992a6b1744cf92d407511432bdc8 }}/financio-api:${{ github.sha }}
        file: Financio/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'financioapistage462d'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c332ad2fc2664223a7d97d70496f3b9e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8fa9992a6b1744cf92d407511432bdc8 }}/financio-api:${{ github.sha }}'
