name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Build solution
        working-directory: Financio/Financio
        run: |
          dotnet restore
          dotnet build

  build-and-push-image:
    needs: build
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: btymo
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        working-directory: Financio
        run: |
          docker build -t btymo/btymo-repo:backend .
          docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker push btymo/btymo-repo:backend
